#+TITLE: javascript學習筆記
#+DATE: <2015-12-11 Thu 18:28>
#+TAGS: javascript
#+LAYOUT: post
#+CATEGORIES: javascript
#+OPTIONS: toc:t \n:t


隨筆亂記
陸續增加中
#+BEGIN_HTML
<!--more-->
#+END_HTML


=The function of javascript is just an Object so it can has properties or functions in it.=

* javascript built-in types
+ =string=
+ =number=
+ =boolean=
+ =null= and =undefined=
+ =object=
+ =symbol= (new to ES6)

* Hoisting
可以想像成所有宣告時機(var a)都被提升到function最開始，更精確的說是scope的最開始
實際上是javascript interpreter將var a = 2分成兩個步驟
declaration(var a)，assignment(a = 2)
所有declaration在compile time完成，assignment在runtime執行
須注意的是ES6新增的block scope variable =let & const=，沒有hoisting機制
當然eval("var a = 2;");這種用法也會破壞hoisting，不過為了效能本來就該避免eval這東西了
#+BEGIN_SRC javascript
var a = 2;

foo();					// works because `foo()`
						// declaration is "hoisted"

function foo() {
	a = 3;

	console.log( a );	// 3

	var a;				// declaration is "hoisted"
						// to the top of `foo()`
}

console.log( a );	// 2
#+END_SRC

* Closure
=Closure is when a function is able to remember and access its lexical scope even when that function is executing outside its lexical scope.=

foo()執行完後，local variable a沒被回收的原因是因為baz -> bar還擁有reference to foo，所以a不會被GC回收 
#+BEGIN_SRC javascript
function foo() {
    var a = 2;

    function bar() {
        console.log( a );
    }

    return bar;
}

var baz = foo();

baz(); // 2 -- Whoa, closure was just observed, man.
#+END_SRC
some useful snippet
#+BEGIN_SRC javascript
function wait(message) {

    setTimeout( function timer(){
        console.log( message );
    }, 1000 );

}

wait( "Hello, closure!" );
#+END_SRC

* Immediately Invoked Function Expressions (IIFEs)
#+BEGIN_SRC javascript
(function IIFE(){
	console.log( "Hello!" );
})();
// "Hello!"
#+END_SRC
* Modules
#+BEGIN_SRC javascript
var foo = (function CoolModule(id) {
    function change() {
        // modifying the public API
        publicAPI.identify = identify2;
    }

    function identify1() {
        console.log( id );
    }

    function identify2() {
        console.log( id.toUpperCase() );
    }

    var publicAPI = {
        change: change,
        identify: identify1
    };

    return publicAPI;
})( "foo module" );

foo.identify(); // foo module
foo.change();
foo.identify(); // FOO MODULE
#+END_SRC
** Modern Modules
module dependency loaders/managers
#+BEGIN_SRC javascript
var MyModules = (function Manager() {
    var modules = {};

    function define(name, deps, impl) {
        for (var i=0; i<deps.length; i++) {
            deps[i] = modules[deps[i]];
        }
        modules[name] = impl.apply( impl, deps );
    }

    function get(name) {
        return modules[name];
    }

    return {
        define: define,
        get: get
    };
})();
#+END_SRC
use above
#+BEGIN_SRC javascript
MyModules.define( "bar", [], function(){
    function hello(who) {
        return "Let me introduce: " + who;
    }

    return {
        hello: hello
    };
} );

MyModules.define( "foo", ["bar"], function(bar){
    var hungry = "hippo";

    function awesome() {
        console.log( bar.hello( hungry ).toUpperCase() );
    }

    return {
        awesome: awesome
    };
} );

var bar = MyModules.get( "bar" );
var foo = MyModules.get( "foo" );

console.log(
    bar.hello( "hippo" )
); // Let me introduce: hippo

foo.awesome(); // LET ME INTRODUCE: HIPPO
#+END_SRC
** Future Modules
ES6新語法，支援File based Modules

bar.js
#+BEGIN_SRC javascript
function hello(who) {
    return "Let me introduce: " + who;
}

export hello;
#+END_SRC
foo.js
#+BEGIN_SRC javascript
// import only `hello()` from the "bar" module
import hello from "bar";

var hungry = "hippo";

function awesome() {
    console.log(
        hello( hungry ).toUpperCase()
    );
}

export awesome;
#+END_SRC
use above
#+BEGIN_SRC javascript
// import the entire "foo" and "bar" modules
module foo from "foo";
module bar from "bar";

console.log(
    bar.hello( "rhino" )
); // Let me introduce: rhino

foo.awesome(); // LET ME INTRODUCE: HIPPO
#+END_SRC
* This
javascript的this與一般OO的this很不一樣，他是runtime時才決定指向哪裡的
詳細決定規則請見以下
** Default Binding
當不滿足以下三種狀況時，this會自動指向global，strict mode下則是undefined
** Implicit Binding
this指向obj2
#+BEGIN_SRC javascript
function foo() {
    console.log( this.a );
}

var obj2 = {
    a: 42,
    foo: foo
};

var obj1 = {
    a: 2,
    obj2: obj2
};

obj1.obj2.foo(); // 42
#+END_SRC
在callback下，容易發生implicitly lost
#+BEGIN_SRC javascript
function foo() {
    console.log( this.a );
}

var obj = {
    a: 2,
    foo: foo
};

var a = "oops, global"; // `a` also property on global object

setTimeout( obj.foo, 100 ); // "oops, global"
#+END_SRC
** Explicit Binding
可利用call、apply來強制綁定this物件，解決上述的implicitly lost
#+BEGIN_SRC javascript
function foo(something) {
    console.log( this.a, something );
    return this.a + something;
}

// simple `bind` helper
// bind obj to this of fn
function bind(fn, obj) {
    return function() {
        return fn.apply( obj, arguments );
    };
}

var obj = {
    a: 2
};

var bar = bind( foo, obj );

var b = bar( 3 ); // 2 3
console.log( b ); // 5
#+END_SRC
ES5內建bind方法可簡單達成上述
#+BEGIN_SRC javascript
function foo(something) {
    console.log( this.a, something );
    return this.a + something;
}

var obj = {
    a: 2
};

var bar = foo.bind( obj );

var b = bar( 3 ); // 2 3
console.log( b ); // 5
#+END_SRC
** New Binding
#+BEGIN_SRC javascript
function foo(a) {
    this.a = a;
}

var bar = new foo( 2 ); // this is binding to bar
console.log( bar.a ); // 2
#+END_SRC
** So How To Determine This

1. Is the function called with =new= (*new binding*)? If so, =this= is the newly constructed object. 

    =var bar = new foo()=

2. Is the function called with =call= or =apply= (*explicit binding*), even hidden inside a =bind= *hard binding*? If so, =this= is the explicitly specified object. 

    =var bar = foo.call( obj2 )=

3. Is the function called with a context (*implicit binding*), otherwise known as an owning or containing object? If so, =this= is *that* context object.

    =var bar = obj1.foo()=

4. Otherwise, default the =this= (*default binding*). If in =strict mode=, pick =undefined=, otherwise pick the =global= object.

    =var bar = foo()=
** Safer this
如果你發現你需要apply或bind的parameter spread、currying功能
但卻不care this到底是什麼，你可能會想用apply(null, [2, 3])
這可能導致this指向global(default binding)
底下是一種比較好的方式，create一個empty object來取代null
#+BEGIN_SRC javascript
function foo(a,b) {
    console.log( "a:" + a + ", b:" + b );
}

// our DMZ empty object
var ø = Object.create( null );

// spreading out array as parameters
foo.apply( ø, [2, 3] ); // a:2, b:3

// currying with `bind(..)`
var bar = foo.bind( ø, 2 );
bar( 3 ); // a:2, b:3
#+END_SRC
** arrow function
ES6新增的arrow function，有著跟一般function不一樣的this行為
其this永遠指向包圍它的function的this，使其在callback中很有用
#+BEGIN_SRC javascript
function foo() {
    setTimeout(() => {
        // `this` here is lexically adopted from `foo()`
        console.log( this.a );
    },100);
}

var obj = {
    a: 2
};

foo.call( obj ); // 2
#+END_SRC
然而在不用arrow function時就已經有好解法了：
#+BEGIN_SRC javascript
function foo() {
    var self = this; // lexical capture of `this`
    setTimeout( function(){
        console.log( self.a );
    }, 100 );
}

var obj = {
    a: 2
};

foo.call( obj ); // 2
#+END_SRC
當然你也能用bind來處理callback的this，這三種方法就是程式風格的不同而已，儘量統一就好
* Object
** Computed Property Names
ES6 adds computed property names, where you can specify an expression, surrounded by a [ ] pair, in the key-name position of an object-literal declaration:
#+BEGIN_SRC javascript 
var prefix = "foo";

var myObject = {
    [prefix + "bar"]: "hello",
    [prefix + "baz"]: "world"
};

myObject["foobar"]; // hello
myObject["foobaz"]; // world
#+END_SRC
常配合ES6新增的Symbol使用
#+BEGIN_SRC javascript
var myObject = {
    [Symbol.Something]: "hello world"
};
#+END_SRC
** Duplicating Objects
Copy Object分成shallow copy and deep copy，其中deep copy可能會出現某些問題
例如以下例子，deep copy將造成infinite circular duplication
#+BEGIN_SRC javascript
function anotherFunction() { /*..*/ }

var anotherObject = {
    c: true
};

var anotherArray = [];

var myObject = {
    a: 2,
    b: anotherObject,   // reference, not a copy!
    c: anotherArray,    // another reference!
    d: anotherFunction
};

anotherArray.push( anotherObject, myObject );
#+END_SRC
若欲複製的object是JSON-safe (that is, can be serialized to a JSON string and then re-parsed to an object with the same structure and values)，我們可以用以下方式做到deep copy
#+BEGIN_SRC javascript
var newObj = JSON.parse( JSON.stringify( someObj ) );
#+END_SRC
shallow copy比較沒有爭議，所以ES6提供以下方式：
#+BEGIN_SRC javascript
var newObj = Object.assign( {}, myObject );

newObj.a;                       // 2
newObj.b === anotherObject;     // true
newObj.c === anotherArray;      // true
newObj.d === anotherFunction;   // true
#+END_SRC
** Property Descriptors
ES5以後才有的功能
+ writable(可否modify)
+ enumerable(可否用for...in遍歷)
+ configurable(可否用difineProperty重新定義 and 可否用delete刪除)

Get Property Descriptors
#+BEGIN_SRC javascript
var myObject = {
    a: 2
};

Object.getOwnPropertyDescriptor( myObject, "a" );
// {
//    value: 2,
//    writable: true,
//    enumerable: true,
//    configurable: true
// }
#+END_SRC

Modify Property Descriptors
#+BEGIN_SRC javascript
var myObject = {};

Object.defineProperty( myObject, "a", {
    value: 2,
    writable: false, // not writable!
    configurable: true,
    enumerable: true
} );

myObject.a = 3;

myObject.a; // 2
#+END_SRC
若是在strict mode，上述會扔出TypeError

** Immutability
以下方式均只能做到shallow immutability. That is, they affect only the object and its direct property characteristics. If an object has a reference to another object (array, object, function, etc), the contents of that object are not affected, and remain mutable.
*** Object Constant
Use writable:false and configurable:false to construct Constant Property
#+BEGIN_SRC javascript
var myObject = {};

Object.defineProperty( myObject, "FAVORITE_NUMBER", {
    value: 42,
    writable: false,
    configurable: false
} );
#+END_SRC
*** Prevent Extensions
#+BEGIN_SRC javascript
var myObject = {
    a: 2
};

Object.preventExtensions( myObject );

myObject.b = 3;
myObject.b; // undefined
#+END_SRC
*** Seal
Object.seal(..) creates a "sealed" object, which means it takes an existing object and essentially calls Object.preventExtensions(..) on it, but also marks all its existing properties as configurable:false.
*** Freeze
Object.freeze(..) creates a frozen object, which means it takes an existing object and essentially calls Object.seal(..) on it, but it also marks all "data accessor" properties as writable:false, so that their values cannot be changed.

若需要deep freeze，可自行recursive Object.freeze()
** Getters & Setters
You will almost certainly want to always declare both getter and setter (having only one or the other often leads to unexpected/surprising behavior)
#+BEGIN_SRC javascript
var myObject = {
    // define a getter for `a`
    get a() {
        return this._a_;
    },

    // define a setter for `a`
    set a(val) {
        this._a_ = val * 2;
    }
};

myObject.a = 2;

myObject.a; // 4
#+END_SRC
** Existence
如何check object是否有某個property
#+BEGIN_SRC javascript
var myObject = {
    a: 2
};

("a" in myObject);              // true
("b" in myObject);              // false

myObject.hasOwnProperty( "a" ); // true
myObject.hasOwnProperty( "b" ); // false
#+END_SRC
in與hasOwnProperty的最大不同處在in會檢查prototype chain而hasOwnProperty不會，需小心的是若object沒有 delegation to Object.prototype，他將不會擁有hasOwnProperty，此時可以使用Object.prototype.hasOwnProperty.call(myObject,"a")來檢查
另外in看起來好像可以這樣用：4 in [2, 4, 6]，但實際上它檢查的是object的property，所以此用法是錯誤的，in不可用來檢查containers是否存在某值
** Enumeration
#+BEGIN_SRC javascript
var myObject = { };

Object.defineProperty(
    myObject,
    "a",
    // make `a` enumerable, as normal
    { enumerable: true, value: 2 }
);

Object.defineProperty(
    myObject,
    "b",
    // make `b` NON-enumerable
    { enumerable: false, value: 3 }
);

myObject.b; // 3
("b" in myObject); // true
myObject.hasOwnProperty( "b" ); // true

// .......

for (var k in myObject) {
    console.log( k, myObject[k] );
}
// "a" 2
#+END_SRC
*Note:* for...in將會travel all values and properties(include prototype chain)，所以建議遍歷object使用for...in loop，遍歷array的話使用一般for loop
#+BEGIN_SRC javascript
var myObject = { };

Object.defineProperty(
    myObject,
    "a",
    // make `a` enumerable, as normal
    { enumerable: true, value: 2 }
);

Object.defineProperty(
    myObject,
    "b",
    // make `b` non-enumerable
    { enumerable: false, value: 3 }
);

myObject.propertyIsEnumerable( "a" ); // true
myObject.propertyIsEnumerable( "b" ); // false

Object.keys( myObject ); // ["a"]
Object.getOwnPropertyNames( myObject ); // ["a", "b"]
#+END_SRC
目前沒有built-in方法可做到list all keys in object include prototype chain，需要自行recursive Object.keys()
** Iteration
for...in loop拿出來的東西會是object的properties，但若我們想直接拿出value呢？
ES6新增的for...of loop可辦到
#+BEGIN_SRC javascript
var myArray = [ 1, 2, 3 ];

for (var v of myArray) {
    console.log( v );
}
// 1
// 2
// 3
#+END_SRC
for...of僅能用在有定義@@iterator的object上，array預設就有，但其他object預設是沒有的
若想用for...of的話還是可以自己定義@@iterator，滿足以下即可：
As long as your iterator returns the expected { value: .. } return values from next() calls, and a { done: true } after the iteration is complete, ES6's for..of can iterate over it.
#+BEGIN_SRC javascript

var myObject = {
    a: 2,
    b: 3
};

Object.defineProperty( myObject, Symbol.iterator, {
    enumerable: false,
    writable: false,
    configurable: true,
    value: function() {
        var o = this;
        var idx = 0;
        var ks = Object.keys( o );
        return {
            next: function() {
                return {
                    value: o[ks[idx++]],
                    done: (idx > ks.length)
                };
            }
        };
    }
} );

// iterate `myObject` manually
var it = myObject[Symbol.iterator]();
it.next(); // { value:2, done:false }
it.next(); // { value:3, done:false }
it.next(); // { value:undefined, done:true }

// iterate `myObject` with `for..of`
for (var v of myObject) {
    console.log( v );
}
// 2
// 3
#+END_SRC
以下是一個利用iterator的亂數產生器
#+BEGIN_SRC javascript
var randoms = {
    [Symbol.iterator]: function() {
        return {
            next: function() {
                return { value: Math.random() };
            }
        };
    }
};

var randoms_pool = [];
for (var n of randoms) {
    randoms_pool.push( n );

    // don't proceed unbounded!
    if (randoms_pool.length === 100) break;
}
#+END_SRC
* ES6新東東
let, const, arrow function, class, module, symbol
